#!/bin/sh

#
# SPD
#

# Lauch spotifyd with cusom args and update bar
# TODO: Add log or find puleaudio workaround for openrc


# if [ $(pidof -sx spotifyd) ]; then
#     echo 'Error: Spotifyd is alrady running'
#     exit 0
# else
#     spotifyd --no-daemon &

#     # wait up to 20 seconds to refresh bar
#     for ((i=0; i<20; i++)); do
# 	# Check if the condition is met
# 	if [ ! $(pidof -x spotifyd) ]; then
# 	    echo "Waiting for spotifyd"
# 	else
# 	    # Condition met, execute the command and break out of the loop
# 	    echo "spotifyd UP"
# 	    pkill -RTMIN+3 dwmblocks && break
# 	fi
# 	sleep 1
#     done
# fi
